### PR TITLE
flipper ios: Pin to some specific versions, to fix build with Xcode 12.5.

### PR DESCRIPTION
**Pull request by chrisbobbe**
Builds are failing with Xcode 12.5, and mine auto-updated this morning; here's a fix. (And a follow-up commit that resolves an unrelated issue.)

I've marked this P0 because iOS development/testing for any purpose (e.g., code review) is halted, for me and for anyone else whose Xcode got (auto-)updated; please let me know if this is wrong. I don't think Apple lets you downgrade Xcode after upgrading?

### CODE REVIEW

**Comment by chrisbobbe** [comment]
It'd be great to know if this breaks builds with Xcode <12.5, I guess, if that's possible.

**Comment by gnprice** [comment]
> I don't think Apple lets you downgrade Xcode after upgrading?

They do:

https://developer.apple.com/download/more/

but it's annoying, partly because it's a >10GB download.

LGTM, merging.

**Comment by gnprice** [comment]
FTR, here's an example of the symptom this fixes. The build failed with the following summary:
```
The following build commands failed:
        CompileC /Users/greg/Library/Developer/Xcode/DerivedData/ZulipMobile-diuocloqwafvdpeozujwphdrhalf/Build/Intermediates.noindex/ArchiveIntermediates/ZulipMobile/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/Flipper-Folly.build/Objects-normal/arm64/DistributedMutex.o /Users/greg/z/mobile/ios/Pods/Flipper-Folly/folly/synchronization/DistributedMutex.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler
```

and the following more detailed error a bit earlier in the log:
```
In file included from /Users/greg/z/mobile/ios/Pods/Flipper-Folly/folly/synchronization/DistributedMutex.cpp:17:
In file included from /Users/greg/z/mobile/ios/Pods/Headers/Private/Flipper-Folly/folly/synchronization/DistributedMutex.h:344:
/Users/greg/z/mobile/ios/Pods/Headers/Private/Flipper-Folly/folly/synchronization/DistributedMutex-inl.h:1051:5: error: 'atomic_notify_one<unsigned long>' is unavailable
    atomic_notify_one(state);
    ^
/Users/greg/z/mobile/ios/Pods/Headers/Private/Flipper-Folly/folly/synchronization/DistributedM
utex-inl.h:1573:5: note: in instantiation of function template specialization 'folly::detail::
distributed_mutex::wakeTimedWaiters<std::__1::atomic<unsigned long>>' requested here
    wakeTimedWaiters(&state_, proxy.timedWaiters_);
    ^
In file included from /Users/greg/z/mobile/ios/Pods/Flipper-Folly/folly/synchronization/Distri
butedMutex.cpp:17:
In file included from /Users/greg/z/mobile/ios/Pods/Headers/Private/Flipper-Folly/folly/synchr
onization/DistributedMutex.h:19:
In file included from /Users/greg/z/mobile/ios/Pods/Headers/Private/Flipper-Folly/folly/Option
al.h:58:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/D
eveloper/SDKs/iPhoneOS13.7.sdk/usr/include/c++/v1/functional:504:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/D
eveloper/SDKs/iPhoneOS13.7.sdk/usr/include/c++/v1/memory:681:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS
13.7.sdk/usr/include/c++/v1/atomic:2140:6: note: 'atomic_notify_one<unsigned long>' has been e
xplicitly marked unavailable here
void atomic_notify_one(atomic<_Tp>* __o) _NOEXCEPT
     ^
```

(That's at v27.163, which doesn't have this fix, and using Xcode 12.5 build 12E262.)
